name: Docker CI/CD

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      - name: Build Docker image
        run: |
          docker build -t vm2rt1ns/container_technologies:latest .

      - name: List Docker images
        run: |
          docker images

      - name: Inspect Docker image
        run: |
          docker inspect vm2rt1ns/container_technologies:latest

      - name: Tag Docker image
        run: |
          docker tag vm2rt1ns/container_technologies:latest vm2rt1ns/container_technologies:latest

      - name: Push Docker image
        run: |
          docker push vm2rt1ns/container_technologies:latest

      - name: Remove Docker image
        run: |
          docker rmi vm2rt1ns/container_technologies:latest
